components:
  vad: 
    name: silero_vad
  chatbot_slm:
    name: rehearsal
    params:
      responses:
        scene1: 
          - text: "你好！没问题，我可以解答一些常见的知识性问题，也可以进行简单的对话。你想先问点什么？"
          - text: "这是由光的散射现象造成的。当阳光进入大气层后，波长较短的蓝光和紫光更容易被大气中的微小颗粒散射，因此人眼看到的天空主要呈现蓝色。"
          - text: "《三体》的作者是中国科幻作家刘慈欣。这个系列主要围绕人类文明与外星文明的碰撞，以及世界观和生存危机展开。"
          - text: "谢谢夸奖。有需要时我还可以再提供更多相关信息。"
          - text: "可以的，你想听哪首诗？"
          - text: "好的，《春晓》的内容是：“春眠不觉晓，处处闻啼鸟。夜来风雨声，花落知多少。”"
          - text: "春眠不觉晓，处处闻啼鸟。夜来风雨声，花落知多少。"
          - text: "春眠不觉晓，处处闻啼鸟。夜来风雨声，花落知多少。"
        scene2:
          - text: "你好！没问题，我可以解答一些常见的知识性问题，也可以进行简单的对话。你想先问点什么？"
          - text: "这是由光的散射现象造成的。当阳光进入大气层后，波长较短的蓝光和紫光更容易被大气中的微小颗粒散射，因此人眼看到的天空主要呈现蓝色。"
          - text: "《三体》的作者是中国科幻作家刘慈欣。这个系列主要围绕人类文明与外星文明的碰撞，以及世界观和生存危机展开。"
          - text: "谢谢夸奖。有需要时我还可以再提供更多相关信息。"
          - text: "可以的，你想听哪首诗？"
          - text: "好的，《春晓》的内容是：“春眠不觉晓，处处闻啼鸟。夜来风雨声，花落知多少。”"
          - text: "春眠不觉晓，处处闻啼鸟。夜来风雨声，花落知多少。"


  text2speech:
    name: rehearsal
    params:
      responses:
        scene1: 
          - audio: "/root/epfs/home/vv/workspace/LegoChat/legochat/services/rehearsal/assets/1-1-1.wav"
          - audio: "/root/epfs/home/vv/workspace/LegoChat/legochat/services/rehearsal/assets/1-1-2.wav"
          - audio: "/root/epfs/home/vv/workspace/LegoChat/legochat/services/rehearsal/assets/1-1-3.wav"
          - audio: "/root/epfs/home/vv/workspace/LegoChat/legochat/services/rehearsal/assets/1-1-4.wav"
          - audio: "/root/epfs/home/vv/workspace/LegoChat/legochat/services/rehearsal/assets/1-2-1.wav"
          - audio: "/root/epfs/home/vv/workspace/LegoChat/legochat/services/rehearsal/assets/1-2-2.wav"
          - audio: "/root/epfs/home/vv/workspace/LegoChat/legochat/services/rehearsal/assets/1-2-3.wav"
        scene2:
          - text: "你好！没问题，我可以解答一些常见的知识性问题，也可以进行简单的对话。你想先问点什么？"
          - text: "这是由光的散射现象造成的。当阳光进入大气层后，波长较短的蓝光和紫光更容易被大气中的微小颗粒散射，因此人眼看到的天空主要呈现蓝色。"
          - text: "《三体》的作者是中国科幻作家刘慈欣。这个系列主要围绕人类文明与外星文明的碰撞，以及世界观和生存危机展开。"
          - text: "谢谢夸奖。有需要时我还可以再提供更多相关信息。"
          - text: "可以的，你想听哪首诗？"
          - text: "好的，《春晓》的内容是：“春眠不觉晓，处处闻啼鸟。夜来风雨声，花落知多少。”"
          - text: "春眠不觉晓，处处闻啼鸟。夜来风雨声，花落知多少。"
  
