components:
  vad: 
    name: silero_vad
  speech2text:
    name: paraformer
  chatbot:
    name: qwen
    params:
      model_name: Qwen/Qwen2.5-7B-Instruct

  text2speech:
    name: sambert_hifigan

  
