components:
  vad: 
    name: silero_vad
  speech2text:
    name: paraformer
  chatbot:
    name: qwen
  text2speech:
    name: sambert_hifigan
    #     name: gptsovits
    #     params:
      #       speaker: om_241114_interview
      #   
