components:
  vad: 
    name: silero_vad
  speech2text:
    name: paraformer
  chatbot:
    name: openai
    params:
      base_url: http://localhost:7000/v1
  text2speech:
    name: streaming_tts
    params:
      base_url: http://localhost:3002
    #     name: gptsovits
    #     params:
      #       speaker: om_241114_interview
      #   
