components:
  vad: 
    name: silero_vad
  denoise:
    name: "null"
  speech2text:
    name: lcy_asr
  chatbot:
    name: "null"
    #     name: openai
    #     params:
    #       base_url: http://localhost:4900/v1
    #       model: Qwen/Qwen2.5-7B-Instruct
  text2speech:
    name: streaming_tts
    params:
      base_url: http://localhost:3002
